### ISSUE TITLE
`DatePickerIOS` has no propType for native prop `RTCDatePicker.onChange` of native type `BOOL`

### ISSUE THREAD

**Issue by jackqqxu** [Johnqing/miumiu#1]
Build Successful. But when run it shows the error : `DatePickerIOS` has no propType for native prop `RTCDatePicker.onChange` of native type `BOOL`

**Comment by jackqqxu** [comment]
I know the reason. the port 8081 was taken by another React app. kill the process. it works.

**Comment by liuqing0224** [comment]
@jackqqxu Thank you very much for your attention to the project. You can use `lsof -i:8081`to check whether the port is occupied.
